development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@salt-prod.stanford.edu:8080/fedora
  solr:
    url: http://salt-prod.stanford.edu:8080/solr
test: &TEST  
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@salt-dev.stanford.edu:8080/fedora
  solr:
    url: http://salt-dev.stanford.edu:8080/solr
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@salt-prod.stanford.edu:8080/fedora
  solr:
    url: http://salt-prod.stanford.edu:8080/solr 
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST
