archivist:
  - snydman
  - mlooney
  - tcramer
  - lmcrae
  - jvine
  - cfitz
  - dougkim
  - jchris
  - eaf
  - wmene
  - savd
  - amorgan2
  - mgolson
  - lowood
  - rns
  - jkeck
  - ndushay
  - gedwards
  - bob
  - alice
  - charlie
donor:
  - kernsc
  - alice
  - francis
researcher:
  - Ronald McDonald
  - alice
patron:
  - Mrs. Quang
