development:
  url: http://localhost:8080/bl_solr
test: &TEST
  url: http://localhost:8080/bl_solr
production:
  url: http://sulwebappdev1.stanford.edu:8100/salt_solr
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST